# Generated by Django 4.1.3 on 2022-11-03 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='contant',
        ),
    ]
