# Generated by Django 4.1.3 on 2022-11-06 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('original_title', models.TextField()),
                ('release_date', models.TextField()),
                ('poster_path', models.TextField()),
                ('backdrop_path', models.TextField(null=True)),
                ('overview', models.TextField()),
                ('adult', models.BooleanField()),
                ('runtime', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('vote_average', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('vote_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('popularity', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('genres', models.ManyToManyField(blank=True, to='movies.genre')),
            ],
        ),
    ]
